image: golang:latest

stages:
  - test

test:
  stage: test
  script:
    - go test -v -race ./...

golangci-lint:
  stage: test
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  script:
    - golangci-lint run ./...
